#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# Este wizard NÃO escreve segredo nenhum em disco. Decisão do Alex em
# 2026-09-11 ("não quero colocar a client_secret no ambiente"): as credenciais
# são lidas do Railway para variáveis DESTE processo e exportadas só para os
# subprocessos de teste. Nada vai para `.env`, nada fica no histórico do shell,
# nada é impresso. Por isso `write_env` não aparece em lugar nenhum aqui — e
# é também por isso que o wizard não é retomável: fechado o processo, as
# credenciais somem e o próximo `railway variables` as busca de novo.
ENV_FILE="/dev/null"

REPO="/Users/acamerini/dev/borisv2"
BRANCH_ESPERADA="v2/interacao-estrutural"
RAILWAY_ENV="production"
TICKER="${TICKER:-PETR4}"
LIMITE_POSSIBILIDADES_S=20

cd "$REPO"

falhou() { printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET"; }
okmsg()  { printf '  %s✓ %s%s\n' "$GREEN" "$1" "$RESET"; }

banner "Fase 24 — aba Opções sobre MCP: o que só você pode fechar"

# ─────────────────────────────────────────────────────────────────────────
stage "Pré-voo: repositório, suíte e build"
say "Antes de tocar em produção, confirma que o que está no disco é o que passou."
note "repo: $REPO · branch esperada: $BRANCH_ESPERADA"

BRANCH_ATUAL=$(git rev-parse --abbrev-ref HEAD)
if [[ "$BRANCH_ATUAL" != "$BRANCH_ESPERADA" ]]; then
  falhou "branch atual é '$BRANCH_ATUAL', esperada '$BRANCH_ESPERADA'"
  confirm "Seguir assim mesmo?" || exit 1
else
  okmsg "branch $BRANCH_ATUAL"
fi

SUJO=$(git status --porcelain --untracked-files=no)
if [[ -n "$SUJO" ]]; then
  warn "há mudanças não commitadas em arquivos rastreados:"
  printf '%s\n' "$SUJO" | sed 's/^/      /'
  confirm "Seguir assim mesmo?" || exit 1
else
  okmsg "árvore limpa (os diretórios não rastreados em .claude/skills/ são esperados)"
fi

say ""
say "Rodando a suíte canônica (pytest + web/tests/*.mjs). Leva ~2 min."
note "se ela acusar ~26 falhas em test_yahoo_*/test_texto_vazio/test_benchmark_ibov,"
note "você está num shell com sandbox de rede: rode este wizard fora dele."
if bash scripts/executar.sh --testes; then
  okmsg "suíte verde"
else
  falhou "a suíte falhou — não publique por cima disso"
  confirm "Continuar assim mesmo (só para inspecionar as etapas seguintes)?" || exit 1
fi

say ""
say "Build do front:"
( cd web && npx vite build >/dev/null 2>&1 ) && okmsg "vite build ok" || { falhou "vite build falhou"; exit 1; }
pause "Enter para seguir"

# ─────────────────────────────────────────────────────────────────────────
stage "Credenciais do Railway (nada toca o disco)"
say "As credenciais do serviço MCP e da IA gerenciada vêm do Railway, em memória."
note "ambiente: $RAILWAY_ENV — a CLI costuma ficar linkada no staging, então o"
note "--environment é explícito em toda chamada deste wizard."

command -v railway >/dev/null 2>&1 || { falhou "railway CLI não encontrada"; exit 1; }
railway whoami >/dev/null 2>&1 || { falhou "railway CLI não autenticada (rode: railway login)"; exit 1; }
okmsg "railway CLI autenticada"

VARS_JSON=$(railway variables --json --environment "$RAILWAY_ENV" 2>/dev/null) || {
  falhou "não consegui ler as variáveis de $RAILWAY_ENV"; exit 1; }

_var() { printf '%s' "$VARS_JSON" | python3 -c 'import json,sys;print(json.load(sys.stdin).get(sys.argv[1],""))' "$1"; }

export MCP_CLIENT_ID="$(_var MCP_CLIENT_ID)"
export MCP_CLIENT_SECRET="$(_var MCP_CLIENT_SECRET)"
export MCP_URL="$(_var MCP_URL)"
export B3_MANAGED_LLM_KEY="$(_var B3_MANAGED_LLM_KEY)"
export B3_MANAGED_LLM_MODEL="$(_var B3_MANAGED_LLM_MODEL)"
export B3_MANAGED_LLM_PROVIDER="$(_var B3_MANAGED_LLM_PROVIDER)"
VARS_JSON=""   # o JSON inteiro sai da memória do shell assim que serviu

for v in MCP_CLIENT_ID MCP_CLIENT_SECRET; do
  [[ -n "${!v}" ]] || { falhou "$v não está definida em $RAILWAY_ENV"; exit 1; }
done
okmsg "MCP_CLIENT_ID e MCP_CLIENT_SECRET carregados (valores nunca exibidos)"
[[ -n "$MCP_URL" ]] && note "MCP_URL: $MCP_URL" || note "MCP_URL ausente — o cliente usa o default do contrato"
if [[ -n "$B3_MANAGED_LLM_KEY" ]]; then
  okmsg "IA gerenciada disponível (${B3_MANAGED_LLM_PROVIDER:-provider?}/${B3_MANAGED_LLM_MODEL:-modelo?})"
else
  warn "B3_MANAGED_LLM_KEY vazia — a etapa 5 (LLM real) vai pular"
fi
pause "Enter para seguir"

# ─────────────────────────────────────────────────────────────────────────
stage "Testes vivos do serviço MCP"
say "Dois testes que só rodam com credencial. Custam ~4 chamadas do teto de 2.000/dia."
step "test_mcp_vivo.py — token no id.semente.dev e uma cadeia real"
step "test_opcoes_paridade_mcp.py::test_paridade_viva — o MOTIVO desta etapa existir:"
note "hoje a paridade só está provada contra fixture derivada do próprio"
note "opcoes_payoff, ou seja, consistência consigo mesmo. Este é o único teste"
note "que confronta a matemática do Boris com a do serviço sobre dado real."

set +e
( cd server && .venv/bin/python -m pytest \
    tests/test_mcp_vivo.py \
    tests/test_opcoes_paridade_mcp.py \
    -q -p no:cacheprovider )
COD_VIVO=$?
set -e
if [[ $COD_VIVO -eq 0 ]]; then
  okmsg "testes vivos verdes — os dois motores concordam sobre dado real"
else
  falhou "testes vivos falharam (código $COD_VIVO)"
  warn "divergência de paridade é o gatilho de consolidação do ADR-027, Decisão 3."
  warn "NÃO publique antes de entender: é a matemática de dinheiro dos dois lados."
  confirm "Seguir mesmo assim?" || exit 1
fi
pause "Enter para seguir"

# ─────────────────────────────────────────────────────────────────────────
stage "Aceite de latência: /possibilidades com N=6 abaixo de ${LIMITE_POSSIBILIDADES_S}s"
say "O custo 2×N+1 está provado por contagem de chamadas; o TEMPO nunca foi medido."
note "13 chamadas ao serviço numa requisição só, com o semáforo de 4 do cliente."
note "Roda contra o app de verdade (TestClient), com o serviço MCP real."

TMPMEDIR=$(mktemp -d)
set +e
B3_DB_PATH="$TMPMEDIR/fase24.db" \
PYTHONPATH="$REPO/server" \
"$REPO/server/.venv/bin/python" - "$TICKER" "$LIMITE_POSSIBILIDADES_S" <<'PYEOF'
import os, sys, time
from fastapi.testclient import TestClient
ticker, limite = sys.argv[1], float(sys.argv[2])
os.environ.setdefault("B3_MCP_COTA_USUARIO_DIA", "200")
from app import main
c = TestClient(main.app)
r = c.post("/api/auth/register", json={"email": "fase24@local.test", "password": "senhaboa123"})
r.raise_for_status()
h = {"authorization": "Bearer " + r.json()["token"]}
leitura = c.get(f"/api/options/mcp/leitura/{ticker}", headers=h)
if leitura.status_code != 200:
    print(f"  leitura falhou: {leitura.status_code} {leitura.text[:200]}"); sys.exit(2)
venc = (leitura.json().get("expirations") or [])[:6]
print(f"  vencimentos abertos em {ticker}: {len(venc)} → {venc}")
if not venc:
    print("  sem vencimento aberto: o aceite N=6 não é exercitável hoje"); sys.exit(3)
t0 = time.perf_counter()
p = c.post("/api/options/mcp/possibilidades",
           json={"ticker": ticker, "direction": "bullish", "lote": 100,
                 "expirations": venc},
           headers=h)
dt = time.perf_counter() - t0
print(f"  HTTP {p.status_code} em {dt:.1f}s (limite do aceite: {limite:.0f}s)")
if p.status_code == 200:
    d = p.json()
    print(f"  chamadasPrevistas={d.get('chamadasPrevistas')} "
          f"possibilidades={len(d.get('possibilidades') or [])} "
          f"cap.usado={(d.get('cap') or {}).get('usado')}")
    montadas = sum(1 for i in (d.get("possibilidades") or []) if i.get("estrutura"))
    print(f"  estruturas montadas: {montadas}/{len(d.get('possibilidades') or [])}")
else:
    print(f"  corpo: {p.text[:300]}")
sys.exit(0 if (p.status_code == 200 and dt < limite) else 1)
PYEOF
COD_LAT=$?
set -e
rm -rf "$TMPMEDIR"
[[ $COD_LAT -eq 0 ]] && okmsg "aceite de latência cumprido" || falhou "aceite de latência NÃO cumprido (código $COD_LAT)"
note "se estourou o tempo: o freio certo é subir o TTL do cache (o dado é EOD),"
note "não baixar N — ver §6 do docs/PLANO-aba-opcoes.md."
pause "Enter para seguir"

# ─────────────────────────────────────────────────────────────────────────
stage "LLM real no compilador NL→DSL"
say "llm._call_llm está substituído em 100% dos testes. Nunca um modelo de verdade"
say "leu o \`system\` montado em runtime do inputSchema de create_setup."
note "é isto que decide se MAX_TOKENS_COMPILADOR = 1500 basta."

if [[ -z "$B3_MANAGED_LLM_KEY" ]]; then
  warn "sem B3_MANAGED_LLM_KEY: etapa pulada"
else
  TMPLLMDIR=$(mktemp -d)
  set +e
  B3_DB_PATH="$TMPLLMDIR/fase24.db" \
  PYTHONPATH="$REPO/server" \
  "$REPO/server/.venv/bin/python" - "$TICKER" <<'PYEOF'
import os, sys
from fastapi.testclient import TestClient
ticker = sys.argv[1]
from app import main
c = TestClient(main.app)
# Primeira conta de um banco vazio vira admin (bootstrap aditivo), então ela
# tem `opcoes.criar_setup` — é o que a rota exige.
r = c.post("/api/auth/register", json={"email": "fase24@local.test", "password": "senhaboa123"})
r.raise_for_status()
tok = r.json()["token"]
h = {"authorization": "Bearer " + tok}
me = c.get("/api/me", headers=h)
perms = (me.json().get("user") or me.json()).get("permissions") or []
print(f"  permissões da conta de teste: {perms}")
if "opcoes.criar_setup" not in perms:
    print("  a conta não recebeu opcoes.criar_setup — a rota vai responder 403"); sys.exit(2)
descricao = (f"Quero um setup para {ticker}: avisar quando o RSI de 14 ficar "
             f"abaixo de 30 e o fechamento estiver acima da média de 200, "
             f"por dois pregões seguidos.")
r = c.post("/api/options/mcp/setups/compilar",
           json={"ticker": ticker, "descricao": descricao}, headers=h)
print(f"  HTTP {r.status_code}")
try:
    d = r.json()
except Exception:
    print("  corpo não-JSON:", r.text[:300]); sys.exit(1)
if r.status_code == 200:
    s = d.get("setup") or {}
    print(f"  status={d.get('status')} name={s.get('name')!r} "
          f"conditions={len(s.get('conditions') or [])} logic={s.get('logic')} "
          f"consecutive_days={s.get('consecutive_days')}")
    print(f"  description preservada: {s.get('description') == descricao}")
    b = d.get("backtest") or {}
    print(f"  backtest: disparos={b.get('disparos')} "
          f"por100={b.get('disparos_por_100_pregoes_avaliaveis')} "
          f"d+5={(b.get('retorno_apos_disparo') or {}).get('d+5')}")
    print("  NADA FOI GRAVADO: é dry-run, confirm=false.")
    sys.exit(0)
print("  detalhe:", str(d)[:500])
sys.exit(1)
PYEOF
  COD_LLM=$?
  set -e
  rm -rf "$TMPLLMDIR"
  if [[ $COD_LLM -eq 0 ]]; then
    okmsg "o modelo compilou a descrição e o serviço validou a semântica"
  else
    falhou "a compilação com LLM real falhou (código $COD_LLM)"
    note "422 compilacao_invalida com \`cru\` truncado = MAX_TOKENS_COMPILADOR curto."
    note "422 setup_invalido com \`problems\` = o modelo compilou, a semântica não passou."
  fi
fi
pause "Enter para seguir"

# ─────────────────────────────────────────────────────────────────────────
stage "Publicar (bump + build + publicar-web.sh)"
warn "Daqui em diante o efeito é para TODOS os usuários."
say "Ordem obrigatória: merge de origin/main → bump → vite build → publicar-web.sh"
note "bump.sh sem argumento pode REBAIXAR produção: ele deriva do BUILD_ID local,"
note "e o publicar-web.sh compara por != , não por ordem. Passe o carimbo à mão."

say ""
say "Carimbo de hoje sugerido (confira o último em produção antes):"
SUGESTAO="F10-$(date +%Y%m%d)-01"
note "sugestão: $SUGESTAO"
say "Em produção agora:"
curl -s https://boris.semente.dev/api/health | sed 's/^/      /' || warn "não consegui consultar /api/health"

say ""
if confirm "Publicar agora?"; then
  ask CARIMBO "Carimbo a publicar (ex.: $SUGESTAO):"
  [[ -n "$CARIMBO" ]] || { falhou "carimbo vazio"; exit 1; }
  say "Sincronizando com origin/main antes do bump…"
  git fetch origin && git merge origin/main --no-edit
  bash scripts/bump.sh "$CARIMBO"
  warn "abra web/src/version.js e server/app/main.py e reescreva o COMENTÁRIO da linha:"
  warn "o script preserva o texto antigo, que vira mentira sobre o que foi publicado."
  pause "Enter quando os comentários estiverem certos"
  ( cd web && npx vite build ) || { falhou "vite build falhou"; exit 1; }
  bash scripts/publicar-web.sh
  say ""
  say "Conferindo produção:"
  sleep 5
  curl -s https://boris.semente.dev/api/health | sed 's/^/      /'
  okmsg "se o build acima é $CARIMBO, front e servidor estão no mesmo carimbo"
else
  note "publicação pulada — rode este wizard de novo quando quiser publicar"
fi
pause "Enter para o checklist final"

# ─────────────────────────────────────────────────────────────────────────
stage "Checkpoint no iPhone (só você pode fazer)"
say "O roteiro do 24-05. Nada aqui é automatizável: é a tela no aparelho."
say ""
step "1. Aba Opções → escolher $TICKER → leitura com pregão e frescor visíveis"
step "2. Analisar → tese de alta → lote 100 → estrutura montada, custo em reais"
step "3. Possibilidades → o custo em chamadas aparece ANTES do toque; disparar"
step "4. Um cartão por vencimento, com payoff desenhado"
step "5. Breakeven em PREÇO, não em reais — conferir a olho"
step "6. Razão ganho/perda visível; com ganho ilimitado, motivo em vez de número"
step "7. Conta admin: Criar setup → descrição em PT → dry-run com backtest → confirmar"
step "8. O setup aparece na lista do ticker sem recarregar"
step "9. Conta comum: a seção Criar setup NÃO existe"
step "10. 375 px sem scroll horizontal; dois temas; prefers-reduced-motion"
say ""
note "defeito encontrado vira quick task, não emenda no plano 24-05."
note "e o app do TestFlight roda o bundle de /Users/acamerini/dev/bolsia/b3-agente,"
note "não este worktree — se for arquivar, é lá (2.0/12)."

finish
